import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, renameSync } from 'node:fs';
import { resolve } from 'node:path';

export type Target = 'local' | 'ssh';

export type Config = {
	target: Target;
	comicsPath: string;
	dataPath: string;
	authToken: string;
	deployHost?: string;
	deployPath?: string;
};

const envPath = resolve(process.cwd(), '.env');

const KEYS = {
	target: 'OMO_DEPLOY_TARGET',
	comicsPath: 'OMO_COMICS_PATH',
	dataPath: 'OMO_DATA_PATH',
	authToken: 'OMO_AUTH_TOKEN',
	deployHost: 'OMO_DEPLOY_HOST',
	deployPath: 'OMO_DEPLOY_PATH',
} as const;

export function generateToken(): string {
	return randomBytes(32).toString('hex');
}

export function readEnv(): Record<string, string> {
	if (!existsSync(envPath)) return {};
	const out: Record<string, string> = {};
	for (const raw of readFileSync(envPath, 'utf8').split('\n')) {
		const line = raw.trim();
		if (!line || line.startsWith('#')) continue;
		const eq = line.indexOf('=');
		if (eq < 0) continue;
		const k = line.slice(0, eq).trim();
		let v = line.slice(eq + 1).trim();
		if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
			v = v.slice(1, -1);
		}
		out[k] = v;
	}
	return out;
}

export function readConfig(): Partial<Config> {
	const env = readEnv();
	const target = env[KEYS.target];
	return {
		target: target === 'local' || target === 'ssh' ? target : undefined,
		comicsPath: env[KEYS.comicsPath] || undefined,
		dataPath: env[KEYS.dataPath] || undefined,
		authToken: env[KEYS.authToken] || undefined,
		deployHost: env[KEYS.deployHost] || undefined,
		deployPath: env[KEYS.deployPath] || undefined,
	};
}

export function writeConfig(config: Config): void {
	const lines = [
		'# Generated by `./omo setup`. Edit by hand or re-run setup.',
		'',
		`${KEYS.target}=${config.target}`,
		`${KEYS.comicsPath}=${config.comicsPath}`,
		`${KEYS.dataPath}=${config.dataPath}`,
		`${KEYS.authToken}=${config.authToken}`,
	];
	if (config.target === 'ssh') {
		lines.push(`${KEYS.deployHost}=${config.deployHost ?? ''}`);
		lines.push(`${KEYS.deployPath}=${config.deployPath ?? ''}`);
	}
	const body = lines.join('\n') + '\n';
	const tmp = envPath + '.tmp';
	writeFileSync(tmp, body, { mode: 0o600 });
	renameSync(tmp, envPath);
}

export function assertComplete(c: Partial<Config>): asserts c is Config {
	const missing: string[] = [];
	if (!c.target) missing.push('target');
	if (!c.comicsPath) missing.push('comics path');
	if (!c.dataPath) missing.push('data path');
	if (c.authToken === undefined) missing.push('auth token');
	if (c.target === 'ssh') {
		if (!c.deployHost) missing.push('deploy host');
		if (!c.deployPath) missing.push('deploy path');
	}
	if (missing.length) {
		throw new Error(
			`.env is missing: ${missing.join(', ')}. Run \`./omo setup\` to configure.`
		);
	}
}

export function renderRemoteEnv(c: Config): string {
	return [
		'# Generated by `./omo deploy`. Runtime config for the omo-core container.',
		`${KEYS.comicsPath}=${c.comicsPath}`,
		`${KEYS.dataPath}=${c.dataPath}`,
		`${KEYS.authToken}=${c.authToken}`,
		'',
	].join('\n');
}
